In [2]:
import numpy as np

In [83]:
def t(x):
    print("----------------------------------------------------------------------------------")
    print(x)
    print('----------------------------------------------------------------------------------')
    return None

In [84]:
t('creating a 1D array')
a=np.array([1,2,3])
print(a)

----------------------------------------------------------------------------------
creating a 1D array
----------------------------------------------------------------------------------
[1 2 3]


In [97]:
t('creating a 2D array')
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b)

----------------------------------------------------------------------------------
creating a 2D array
----------------------------------------------------------------------------------
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [98]:
t('Indexing through the Numpy array')
print(b[0])
print(b[0][0])

----------------------------------------------------------------------------------
Indexing through the Numpy array
----------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [110]:
t('Different methods available in Numpy Object')
print(b.ndim,"-> The dimension of the Array") 
print(b.dtype,"-> The datatype of the Array")
print(b.itemsize,"-> The size of the Data type in bits")
print(b.size,'->Numeber of elements in the array')
print(b.shape,'-> returns a tuple of the length of each dimension of the array')

----------------------------------------------------------------------------------
Different methods available in Numpy Object
----------------------------------------------------------------------------------
3 -> The dimension of the Array
int32 -> The datatype of the Array
4 -> The size of the Data type in bits
9 ->Numeber of elements in the array
(1, 3, 3) -> returns a tuple of the length of each dimension of the array


In [108]:
t("Data Type of the Array")
t('Initializing a int data type array')
x=np.array([1,2,3],dtype=int)
print(x)
t('Inializing a float data type array')
x=np.array([1,2,3],dtype=float)
print(x)
t('Initializing a complex data type array')
x=np.array([1,2,3],dtype=complex)
print(x)

----------------------------------------------------------------------------------
Data Type of the Array
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
Initializing a int data type array
----------------------------------------------------------------------------------
[1 2 3]
----------------------------------------------------------------------------------
Inializing a float data type array
----------------------------------------------------------------------------------
[1. 2. 3.]
----------------------------------------------------------------------------------
Initializing a complex data type array
----------------------------------------------------------------------------------
[1.+0.j 2.+0.j 3.+0.j]


In [113]:
t("Declaring special type of Arrays")
t("In Data Science often we require matrices/arrays filled with 0's or 1's")
t("Matrix of 0's")
x=np.zeros((3,4))
print(x)
t("Matrix of 1's")
x=np.ones((3,4))
print(x)

----------------------------------------------------------------------------------
Declaring special type of Arrays
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
In Data Science often we require matrices/arrays filled with 0's or 1's
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
Matrix of 0's
----------------------------------------------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------------------------------------------------------------------------
Matrix of 1's
----------------------------------------------------------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [116]:
t("creating a 1D array of sequential numbers")
# arange is similar to range in native Python
x=np.arange(0,10) 
print(x)
t("creating a 1D array of sequential numbers with increments")
x=np.arange(0,10,2)#increment
print(x)

----------------------------------------------------------------------------------
creating a 1D array of sequential numbers
----------------------------------------------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
----------------------------------------------------------------------------------
creating a 1D array of sequential numbers with increments
----------------------------------------------------------------------------------
[0 2 4 6 8]


In [118]:
t('Creating a 1D array of linearly spaced numbers between 2 numbers')
x=np.linspace(1,10,7)
print(x)

----------------------------------------------------------------------------------
Creating a 1D array of linearly spaced numbers between 2 numbers
----------------------------------------------------------------------------------
[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [127]:
t('Reshaping an array')
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape)
y=x.reshape(1,9)
print(y.shape)

----------------------------------------------------------------------------------
Reshaping an array
----------------------------------------------------------------------------------
(3, 3)
(1, 9)


In [134]:
t('To convert any dimension array to 1D array')
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.ravel())

----------------------------------------------------------------------------------
To convert any dimension array to 1D array
----------------------------------------------------------------------------------
[1 2 3 4 5 6 7 8 9]


In [141]:
t("Some statistical measures")
print(x.min(),'-> prints the minimum number in the whole array')
print(x.max(),'->prints the maximum number in the whole array')
print(x.sum(),'->prints the sum of all numbers')
t("Sum across axis 1") #Column sum
print(x.sum(axis=1))
t("Sum across axis 0") #Row sum
print(x.sum(axis=0))
t("Square Root of all the numbers in the array")
print(np.sqrt(x))

----------------------------------------------------------------------------------
Some statistical measures
----------------------------------------------------------------------------------
1 -> prints the minimum number in the whole array
9 ->prints the maximum number in the whole array
45 ->prints the sum of all numbers
----------------------------------------------------------------------------------
Sum across axis 1
----------------------------------------------------------------------------------
[ 6 15 24]
----------------------------------------------------------------------------------
Sum across axis 0
----------------------------------------------------------------------------------
[12 15 18]
----------------------------------------------------------------------------------
Square Root of all the numbers in the array
----------------------------------------------------------------------------------
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [

In [142]:
t("Some Mathematical Operations on Numpy Arrays")
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
t('a')
print(a)
t('b')
print(b)
t('a+b')
print(a+b)
t('a*b')
print(a*b)
t('a/b')
print(a/b)

----------------------------------------------------------------------------------
Some Mathematical Operations on Numpy Arrays
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
a
----------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------
b
----------------------------------------------------------------------------------
[[ 7  8  9]
 [10 11 12]]
----------------------------------------------------------------------------------
a+b
----------------------------------------------------------------------------------
[[ 8 10 12]
 [14 16 18]]
----------------------------------------------------------------------------------
a*b
----------------------------------------------------------------------------------
[[ 7 16 27]
 [40 55 72]]
-------------------

In [144]:
#Thats it for the Intro To Numpy ipynb
t("Akshar")

----------------------------------------------------------------------------------
Akshar
----------------------------------------------------------------------------------
